[tasks.setup]
description = "Configure a new machine"
depends = ["install-homebrew", "install-packages", "setup-fish"]

[tasks.install-homebrew]
description = "Install Homebrew if not already installed"
run = """
if ! command -v brew &> /dev/null; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Add Homebrew to PATH based on platform
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    if [[ $(uname -m) == "arm64" ]]; then
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
      eval "$(/opt/homebrew/bin/brew shellenv)"
    else
      echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.zprofile
      eval "$(/usr/local/bin/brew shellenv)"
    fi
  else
    # Linux
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  fi

  echo "Homebrew installed successfully!"
else
  echo "Homebrew is already installed."
fi
"""

[tasks.install-packages]
description = "Install packages from Brewfile"
depends = ["install-homebrew"]
run = """
brew bundle install
"""

[tasks.setup-fish]
description = "Setup fish as the default shell"
depends = ["install-packages"]
run = ["./scripts/use-fish.sh", "./scripts/configure-fish-brew.sh"]
depends_post = []
